### ISSUE TITLE
When you archive a document in prismic, and you load this block on a page as a static block the page breaks

### ISSUE THREAD

**Issue by WouterSteen** [elgentos/magento2-prismicio#107]
Ivo can reproduce this, he will enter some more details :)

**Comment by JeroenBoersma** [comment]
yes, if you have no content for a given content type, so zero documents, prismic will throw a 400 error...

this is because you request a content type that "doesn't" exist in the API end!

just always create a "fake/unused" document of any type and you'll be fine
