### ISSUE TITLE
Parse 3rd party scripts

### ISSUE THREAD

**Issue by WouterSteen** [elgentos/magento2-prismicio#11]
![image](https://user-images.githubusercontent.com/5089604/58464131-69d00100-8135-11e9-86ce-21ed070bcc92.png)

**Comment by WouterSteen** [comment]
`<block class="Elgentos\PrismicIO\Block\Dom\RichText" name="product_category_selector.oembed_code" template="oembed_code" />`

**Comment by JeroenBoersma** [comment]
the code wasn't escaped for the debug section, so it was just invisible to you, this is already resolved
