### ISSUE TITLE
Web link: {{relative}}  in RichText field wouldn't be replaced

### ISSUE THREAD

**Issue by henkvalk** [elgentos/magento2-prismicio#36]
When adding a {{relative}} link inside a RichText field, the   `https://{{relative}}` wouldn't be replaced for the store URL.

![screenshot-vechtsportonline prismic io-2020 07 29-16_08_41](https://user-images.githubusercontent.com/8955854/91971767-05c5c080-ed1a-11ea-98c4-2fe042056ba8.jpg)
![Schermafbeelding_2020-07-29_om_16 10 01](https://user-images.githubusercontent.com/8955854/91971771-078f8400-ed1a-11ea-9f4c-fcf738b906ed.png)

**Comment by peterjaap** [comment]
@henkvalk are you using the `\Elgentos\PrismicIO\Block\Dom\Link` class? It should get replaced there, see https://github.com/elgentos/magento2-prismicio/blob/master/Block/Dom/Link.php#L21

**Comment by peterjaap** [comment]
Oh wait sorry, you're using the `\Elgentos\PrismicIO\Block\Dom\RichText` of course.

**Comment by peterjaap** [comment]
@JeroenBoersma can't we also do the `$findAndReplaceBaseUrl` in the `LinkResolver`? For example, here; https://github.com/elgentos/magento2-prismicio/blob/master/ViewModel/LinkResolver.php#L208?

**Comment by peterjaap** [comment]
The urls found in RichText are now also converted using relative links; https://github.com/elgentos/magento2-prismicio/blob/master/Block/Dom/RichText.php#L44
