### ISSUE TITLE
Implement SliceMachine for Magento

### ISSUE THREAD

**Issue by JeroenBoersma** [elgentos/magento2-prismicio#59]
https://github.com/prismicio/slice-machine/tree/master/packages/slice-machine

**Comment by peterjaap** [comment]
Basically SliceMachine could be implemented by creating [stubs](https://github.com/elgentos/magento2-prismicio/tree/master/stubs/default) based on the SliceMachine's JSON output and then use the [scaffold command](https://github.com/elgentos/magento2-prismicio/blob/master/Console/Command/Scaffold.php).

**Comment by JeroenBoersma** [comment]
This is now finished in the 2.0.0 release
