### ISSUE TITLE
Implement new Prismic toolbar

### ISSUE THREAD

**Issue by JeroenBoersma** [elgentos/magento2-prismicio#63]
![image](https://user-images.githubusercontent.com/1163348/167627753-b6a309de-1dc5-4588-95c1-17f421dbd20d.png)

https://prismic.io/docs/technologies/preview-drafts-vanilla-javascript

```diff
<!-- Here is your Prismic Toolbar script -->
+   <script async defer src="https://static.cdn.prismic.io/prismic.js?new=true&repo=your-repo-name"></script>
```

**Comment by peterjaap** [comment]
Done in the latest veresion!
