### ISSUE TITLE
Add FormKey by default

### ISSUE THREAD

**Issue by henkvalk** [elgentos/magento2-prismicio#72]
Maybe an idea to add the FormKey by default inside the Prismic Page. This because almost every webshop have an newsletter subscription form inside the footer. When a customer filled in the email address to subscribe, the page will give an error because of the missing formkey

**Comment by JeroenBoersma** [comment]
This is part of default Magento... There is no need to add this.

By default the form key is added on every page:

`vendor/magento/module-theme/view/frontend/layout/default.xml`:
```xml
        <referenceContainer name="content">
            <block class="Magento\Framework\View\Element\FormKey" name="formkey"/>
        </referenceContainer>
```

If it is not added to the page that would be another problem in your theme. Sorry I cannot help you out here

**Comment by henkvalk** [comment]
No prob. already add it manual
